#!/bin/bash

maim /tmp/screen.png
convert /tmp/screen.png -scale 5% -scale 2020% /tmp/screen.png
convert -gravity center -composite /tmp/screen.png /home/$USER/Bin/lock.png /tmp/screen.png
i3lock -u -i /tmp/screen.png
xset dpms force standby
rm /tmp/screen.png
# slock
