#!/usr/bin/env sh

WIFI_DEETS="Not connected"
BATTERY_DEETS="No battery present"
TIME_DEETS=$(date "+%X")
DATE_DEETS=$(date "+%x")
VOLUME_DEETS=" 0%"
TRACK_DEETS="Nothing playing"

if [[ `uname` == "Linux" ]]; then
  # WIFI_DEETS=`iwconfig 2> /dev/null | grep -o 'ESSID:.*' | cut -c7- | tr -d '"' | sed 's/ *$//g'`
  WIFI_DEETS=`iw dev | grep Interface | awk '{ print $2 }' | xargs -I "{}" iw dev "{}" link | grep SSID | sed 's/SSID\://' | awk '{$1=$1};1'`
  echo "$WIFI_DEETS"
  BATTERY_DEETS=`acpi | cut -c12-`

  if [[ $WIFI_DEETS == "" ]]; then
    WIFI_DEETS='Disabled / Disconnected'
  fi

  VOLUME_DEETS=`pulseaudio-ctl | grep Volume | awk -F: '{ print $2 }' | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"`
  MUTED_DEETS=`pulseaudio-ctl | grep muted | awk -F: '{ print $2 }' | head -1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"`

  if [[ $MUTED_DEETS == " yes" ]]; then
    VOLUME_DEETS="$VOLUME_DEETS (muted)"
  fi

  if [[ $(playerctl -l) == *"spotify"* ]]; then
    TRACK_DEETS="$(playerctl metadata "xesam:artist") - $(playerctl metadata "xesam:title") ($(playerctl status))"
  else
    TRACK_DEETS="Nothing playing"
  fi
else
  if [[ $(sysctl -n hw.sensors.acpibat0) != '' ]]; then
    bat0full=$(sysctl -n hw.sensors.acpibat0.amphour0 | sed s/.A.*//)
    bat0warn=$(sysctl -n hw.sensors.acpibat0.amphour1 | sed s/.A.*//)
    bat0low=$(sysctl -n hw.sensors.acpibat0.amphour2 | sed s/.A.*//)
    bat0now=$(sysctl -n hw.sensors.acpibat0.amphour3 | sed s/.A.*//)

    # Get the battery capacity in percentage
    bat0cap=`echo "100 * ${bat0now} / ${bat0full}" | bc`
    bat0p="$bat0cap%"

    # Get the charging status of the battery, replace with symbols
    bat0s=$(sysctl -n hw.sensors.acpibat0.raw0 | sed 's/'0'.*//; s/'1'.*/-/; s/'2'.*/+/; s/'4'.*/!/')
  else
    bat0p=`echo ""`
    bat0s=`echo ""`
  fi

  WIFI_DEETS=`ifconfig iwn0 | grep nwid | sed -e 's/ieee80211: nwid\(.*\)chan.*bssid.*/\1/' | tr -d '[[:space:]]'`
  BATTERY_DEETS="${bat0p} (${bat0s})"
fi

ratpoison -c "echo $(echo "Volume: $VOLUME_DEETS"; echo "Music:   $TRACK_DEETS"; echo "Wifi:    $WIFI_DEETS"; echo "Battery: $BATTERY_DEETS"; echo "Date:    $DATE_DEETS"; echo "Time:    $TIME_DEETS";)"
