#!/bin/bash

source "$HOME/Bin/installed"

if [[ $(program_is_installed "pulseaudio-ctl") == 1 ]]; then
  echo "pulse ctl $1"
  pulseaudio-ctl $1 3
else
  if [ $1 == "mute" ]; then
    CURRENT_STATE=`amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]'`

    if [[ $CURRENT_STATE == '[on]' ]]; then
      amixer set Master mute
    else
      amixer set Master unmute
      amixer set Headphone unmute
    fi
  else
    if [ $1 == "up" ]; then
      VALUE=5+
    else
      VALUE=5-
    fi

    amixer set Master $VALUE
  fi
fi
